server:
  port: 8080
#  servlet:
#    context-path: /redis-stream-example

spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
  data:
    redis:
      port: 6379
      host: localhost

redis-stream-example:
  stream-key: job_queue

#actuator 설정 consumer에서 필요
#management:
#  endpoint:
#    health:
#      probes:
#        enabled: true
#      show-details: always
#      group:
#        liveness:
#          - redis
#          - redisStream
#        readiness:
#          - redis
#          - redisStream
